apiVersion: v1
kind: ConfigMap
metadata:
  name: phone-games-config
  namespace: phone-games
data:
  NODE_ENV: "production"
  PORT: "4000"
  # WhatsApp Configuration
  WHATSAPP_API_URL: "https://graph.facebook.com/v22.0"
  WHATSAPP_PHONE_NUMBER_ID: "745990838608160"
  # Add other non-sensitive config here
  TWILIO_WHATSAPP_FROM: "14155238886"
  PUBLIC_URL: "https://api-phone-games.0xaace.xyz"